name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Tntry point
      run: sh programs/ubuntu-20.04/start.sh

    - name: Install AWS CLI
      run: sh programs/ubuntu-20.04/aws.sh

    - name: Install GIT
      run: sh programs/ubuntu-20.04/git.sh

    # - name: Install PHP
    #   run: sh programs/ubuntu-20.04/php.sh

    - name: Install DBeaver
      run: sh programs/ubuntu-20.04/dbeaver.sh

    - name: Install PostgreSQL
      run: sh programs/ubuntu-20.04/postgresql.sh

    # - name: Install Docker
    #   run: sh programs/ubuntu-20.04/docker.sh

    # - name: Install Evernote
    #   run: sh programs/ubuntu-20.04/evernote.sh

    # - name: Install Java
    #   run: sh programs/ubuntu-20.04/java.sh

    # - name: Install Microsoft Teams
    #   run: sh programs/ubuntu-20.04/ms_teams.sh

    - name: Install Zsh
      run: sh programs/ubuntu-20.04/zsh.sh

    - name: Install Node.js and NVM
      run: sh programs/ubuntu-20.04/node_nvm.sh

    - name: Install Terraform
      run: sh programs/ubuntu-20.04/terraform.sh

    # - name: Install Python
    #   run: sh programs/ubuntu-20.04/python.sh

    - name: Install Slack
      run: sh programs/ubuntu-20.04/slack.sh

    - name: Install Yarn
      run: sh programs/ubuntu-20.04/yarn.sh

    # - name: Install Zoom
    #   run: sh programs/ubuntu-20.04/zoom.sh

    - name: Install VS Code
      run: sh programs/ubuntu-20.04/vscode.sh

    - name: Install Discord
      run: sh programs/ubuntu-20.04/discord.sh

    # - name: Install MongoDB
    #   run: sh programs/ubuntu-20.04/mongodb.sh

    # - name: Install Redis
    #   run: sh programs/ubuntu-20.04/redis.sh
