name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Tntry point
      run: sh programs/start.sh

    - name: Install AWS CLI
      run: sh programs/aws.sh

    - name: Install GIT
      run: sh programs/git.sh

    # - name: Install PHP
    #   run: sh programs/php.sh

    - name: Install DBeaver
      run: sh programs/dbeaver.sh

    - name: Install PostgreSQL
      run: sh programs/postgresql.sh

    # - name: Install Docker
    #   run: sh programs/docker.sh

    # - name: Install Evernote
    #   run: sh programs/evernote.sh

    # - name: Install Java
    #   run: sh programs/java.sh

    # - name: Install Microsoft Teams
    #   run: sh programs/ms_teams.sh

    - name: Install Zsh
      run: sh programs/zsh.sh

    - name: Install Node.js and NVM
      run: sh programs/node_nvm.sh

    - name: Install Terraform
      run: sh programs/terraform.sh

    # - name: Install Python
    #   run: sh programs/python.sh

    - name: Install Slack
      run: sh programs/slack.sh

    - name: Install Yarn
      run: sh programs/yarn.sh

    # - name: Install Zoom
    #   run: sh programs/zoom.sh

    - name: Install VS Code
      run: sh programs/vscode.sh

    - name: Install Discord
      run: sh programs/discord.sh

    # - name: Install MongoDB
    #   run: sh programs/mongodb.sh

    # - name: Install Redis
    #   run: sh programs/redis.sh
